#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload_runtime.php';

use App\DiffRecipeVersionsCommand;
use App\GenerateFlexIndexCommand;
use App\LintManifestsCommand;
use App\LintPackagesCommand;
use App\LintPullRequestCommand;
use App\LintYamlCommand;
use App\ListUnpatchedPackagesCommand;
use Symfony\Component\Console\Application;

return function() {
    $app = new Application();

    $app->add(new DiffRecipeVersionsCommand());
    $app->add(new GenerateFlexIndexCommand());
    $app->add(new LintManifestsCommand());
    $app->add(new LintPackagesCommand());
    $app->add(new LintPullRequestCommand());
    $app->add(new LintYamlCommand());
    $app->add(new ListUnpatchedPackagesCommand());

    return $app;
};
